window.arcadeCatalog = {
  games: [
    {
      id: "star",
      title: "星落接接乐",
      description: "接住星星、躲开炸弹，60 秒冲分。",
      genre: "动作反应",
      difficulty: "简单上手",
      duration: "1 分钟",
      category: "动作",
      icon: "✦",
      coverLabel: "60 秒冲分",
      coverNote: "闪避炸弹",
      hotRank: 3,
      tags: ["手速", "躲避", "冲榜"],
      coverA: "#ffd166",
      coverB: "#7ce7ff",
    },
    {
      id: "ddz",
      title: "斗地主小游戏",
      description: "单机快速局，和两个 AI 对战。",
      genre: "牌类策略",
      difficulty: "中等",
      duration: "3-5 分钟",
      category: "牌类",
      icon: "♠",
      coverLabel: "快速叫地主",
      coverNote: "AI 对战",
      hotRank: 6,
      tags: ["策略", "卡牌", "压制"],
      coverA: "#ff9f68",
      coverB: "#ffd166",
    },
    {
      id: "ttt",
      title: "井字棋",
      description: "经典三连线，适合快速来一局。",
      genre: "轻策略",
      difficulty: "简单",
      duration: "30 秒",
      category: "策略",
      icon: "◉",
      coverLabel: "三连即胜",
      coverNote: "快节奏对局",
      hotRank: 8,
      tags: ["经典", "策略", "速战"],
      coverA: "#7ef0b2",
      coverB: "#7ce7ff",
    },
    {
      id: "memory",
      title: "记忆翻牌",
      description: "翻开相同图案完成配对。",
      genre: "记忆益智",
      difficulty: "中等",
      duration: "2 分钟",
      category: "益智",
      icon: "☻",
      coverLabel: "8 组配对",
      coverNote: "记住位置",
      hotRank: 7,
      tags: ["记忆", "翻牌", "配对"],
      coverA: "#7ce7ff",
      coverB: "#95a7ff",
    },
    {
      id: "mole",
      title: "打地鼠",
      description: "30 秒快打模式，拼手速和眼力。",
      genre: "极限反应",
      difficulty: "刺激",
      duration: "30 秒",
      category: "反应",
      icon: "⚡",
      coverLabel: "30 秒挑战",
      coverNote: "地鼠快打",
      hotRank: 5,
      tags: ["手速", "点击", "反应"],
      coverA: "#ff6d83",
      coverB: "#ffd166",
    },
    {
      id: "snake",
      title: "贪吃蛇",
      description: "吃豆变长，撞墙或撞自己就结束。",
      genre: "经典街机",
      difficulty: "中等",
      duration: "2-4 分钟",
      category: "街机",
      icon: "▣",
      coverLabel: "越吃越长",
      coverNote: "经典重玩",
      hotRank: 2,
      tags: ["街机", "成长", "走位"],
      coverA: "#7ef0b2",
      coverB: "#48b87a",
    },
    {
      id: "2048",
      title: "2048",
      description: "滑动数字方块，合成更大的数字。",
      genre: "数字益智",
      difficulty: "耐玩",
      duration: "3-8 分钟",
      category: "益智",
      icon: "2048",
      coverLabel: "数字合成",
      coverNote: "一步步叠高",
      hotRank: 4,
      tags: ["数字", "合成", "耐玩"],
      coverA: "#ffd166",
      coverB: "#ff9f68",
    },
    {
      id: "rps",
      title: "石头剪刀布",
      description: "三局两胜也行，连续挑战也行。",
      genre: "休闲对抗",
      difficulty: "轻松",
      duration: "10 秒",
      category: "休闲",
      icon: "✌",
      coverLabel: "即点即玩",
      coverNote: "三局对决",
      hotRank: 10,
      tags: ["休闲", "对抗", "摸鱼"],
      coverA: "#ff8c7a",
      coverB: "#ff6d83",
    },
    {
      id: "reaction",
      title: "反应速度测试",
      description: "等信号变绿后立刻点击，测你的真实反应。",
      genre: "测试挑战",
      difficulty: "极简",
      duration: "15 秒",
      category: "反应",
      icon: "⏱",
      coverLabel: "真实反应",
      coverNote: "别抢点",
      hotRank: 9,
      tags: ["测试", "反应", "极简"],
      coverA: "#7ce7ff",
      coverB: "#7ef0b2",
    },
    {
      id: "breakout",
      title: "打砖块",
      description: "接住小球，清光砖块就过关。",
      genre: "经典街机",
      difficulty: "中等偏上",
      duration: "2-5 分钟",
      category: "街机",
      icon: "▤",
      coverLabel: "24 块清屏",
      coverNote: "反弹闯关",
      hotRank: 1,
      tags: ["闯关", "街机", "弹球"],
      coverA: "#ffd166",
      coverB: "#ff6d83",
    },
  ],
};
