window.arcadeCatalog = {
  games: [
    {
      id: "star",
      title: "星落接接乐",
      description: "接住星星、躲开炸弹，60 秒冲分。",
      genre: "动作反应",
      difficulty: "简单上手",
      duration: "1 分钟",
      category: "动作",
      icon: "✦",
      coverLabel: "60 秒冲分",
      coverNote: "闪避炸弹",
      hotRank: 3,
      tags: ["手速", "躲避", "冲榜"],
      coverA: "#ffd166",
      coverB: "#7ce7ff",
    },
    {
      id: "ddz",
      title: "斗地主小游戏",
      description: "单机快速局，和两个 AI 对战。",
      genre: "牌类策略",
      difficulty: "中等",
      duration: "3-5 分钟",
      category: "牌类",
      icon: "♠",
      coverLabel: "快速叫地主",
      coverNote: "AI 对战",
      hotRank: 6,
      tags: ["策略", "卡牌", "压制"],
      coverA: "#ff9f68",
      coverB: "#ffd166",
    },
    {
      id: "ttt",
      title: "井字棋",
      description: "经典三连线，适合快速来一局。",
      genre: "轻策略",
      difficulty: "简单",
      duration: "30 秒",
      category: "策略",
      icon: "◉",
      coverLabel: "三连即胜",
      coverNote: "快节奏对局",
      hotRank: 8,
      tags: ["经典", "策略", "速战"],
      coverA: "#7ef0b2",
      coverB: "#7ce7ff",
    },
    {
      id: "memory",
      title: "记忆翻牌",
      description: "翻开相同图案完成配对。",
      genre: "记忆益智",
      difficulty: "中等",
      duration: "2 分钟",
      category: "益智",
      icon: "☻",
      coverLabel: "8 组配对",
      coverNote: "记住位置",
      hotRank: 7,
      tags: ["记忆", "翻牌", "配对"],
      coverA: "#7ce7ff",
      coverB: "#95a7ff",
    },
    {
      id: "mole",
      title: "打地鼠",
      description: "30 秒快打模式，拼手速和眼力。",
      genre: "极限反应",
      difficulty: "刺激",
      duration: "30 秒",
      category: "反应",
      icon: "⚡",
      coverLabel: "30 秒挑战",
      coverNote: "地鼠快打",
      hotRank: 5,
      tags: ["手速", "点击", "反应"],
      coverA: "#ff6d83",
      coverB: "#ffd166",
    },
    {
      id: "snake",
      title: "贪吃蛇",
      description: "吃豆变长，撞墙或撞自己就结束。",
      genre: "经典街机",
      difficulty: "中等",
      duration: "2-4 分钟",
      category: "街机",
      icon: "▣",
      coverLabel: "越吃越长",
      coverNote: "经典重玩",
      hotRank: 2,
      tags: ["街机", "成长", "走位"],
      coverA: "#7ef0b2",
      coverB: "#48b87a",
    },
    {
      id: "2048",
      title: "2048",
      description: "滑动数字方块，合成更大的数字。",
      genre: "数字益智",
      difficulty: "耐玩",
      duration: "3-8 分钟",
      category: "益智",
      icon: "2048",
      coverLabel: "数字合成",
      coverNote: "一步步叠高",
      hotRank: 4,
      tags: ["数字", "合成", "耐玩"],
      coverA: "#ffd166",
      coverB: "#ff9f68",
    },
    {
      id: "rps",
      title: "石头剪刀布",
      description: "三局两胜也行，连续挑战也行。",
      genre: "休闲对抗",
      difficulty: "轻松",
      duration: "10 秒",
      category: "休闲",
      icon: "✌",
      coverLabel: "即点即玩",
      coverNote: "三局对决",
      hotRank: 10,
      tags: ["休闲", "对抗", "摸鱼"],
      coverA: "#ff8c7a",
      coverB: "#ff6d83",
    },
    {
      id: "reaction",
      title: "反应速度测试",
      description: "等信号变绿后立刻点击，测你的真实反应。",
      genre: "测试挑战",
      difficulty: "极简",
      duration: "15 秒",
      category: "反应",
      icon: "⏱",
      coverLabel: "真实反应",
      coverNote: "别抢点",
      hotRank: 9,
      tags: ["测试", "反应", "极简"],
      coverA: "#7ce7ff",
      coverB: "#7ef0b2",
    },
    {
      id: "breakout",
      title: "打砖块",
      description: "接住小球，清光砖块就过关。",
      genre: "经典街机",
      difficulty: "中等偏上",
      duration: "2-5 分钟",
      category: "街机",
      icon: "▤",
      coverLabel: "24 块清屏",
      coverNote: "反弹闯关",
      hotRank: 1,
      tags: ["闯关", "街机", "弹球"],
      coverA: "#ffd166",
      coverB: "#ff6d83",
    },
    {
      id: "gomoku",
      title: "五子棋",
      description: "经典连珠玩法，先连成五子获胜。",
      genre: "棋类对弈",
      difficulty: "中等",
      duration: "3-6 分钟",
      category: "棋类",
      icon: "●",
      coverLabel: "连成五子",
      coverNote: "黑白对战",
      hotRank: 11,
      tags: ["棋类", "连线", "经典"],
      coverA: "#d4d4d4",
      coverB: "#8f8f8f",
    },
    {
      id: "liuzi",
      title: "六子棋",
      description: "在更大的棋盘上抢先连成六子。",
      genre: "棋类对弈",
      difficulty: "中等偏上",
      duration: "4-7 分钟",
      category: "棋类",
      icon: "◎",
      coverLabel: "连成六子",
      coverNote: "更长连线",
      hotRank: 12,
      tags: ["棋类", "连线", "策略"],
      coverA: "#c8c8c8",
      coverB: "#ffd166",
    },
    {
      id: "connect4",
      title: "四子棋",
      description: "像投币一样落子，横竖斜四连即胜。",
      genre: "落子策略",
      difficulty: "简单上手",
      duration: "2-4 分钟",
      category: "棋类",
      icon: "◍",
      coverLabel: "四连即胜",
      coverNote: "纵横堵截",
      hotRank: 13,
      tags: ["棋类", "落子", "对弈"],
      coverA: "#ff9f68",
      coverB: "#7ce7ff",
    },
    {
      id: "reversi",
      title: "黑白棋",
      description: "夹住对方棋子即可翻面，最终占格更多者胜。",
      genre: "翻子策略",
      difficulty: "中等",
      duration: "4-8 分钟",
      category: "棋类",
      icon: "◐",
      coverLabel: "翻面扩张",
      coverNote: "地盘争夺",
      hotRank: 14,
      tags: ["棋类", "翻子", "策略"],
      coverA: "#7ef0b2",
      coverB: "#0f3b2f",
    },
    {
      id: "checkers",
      title: "跳棋对战",
      description: "简化跳棋规则，吃子优先，率先清空对手获胜。",
      genre: "跳跃棋类",
      difficulty: "中等",
      duration: "3-6 分钟",
      category: "棋类",
      icon: "⬢",
      coverLabel: "跳吃对手",
      coverNote: "步步压制",
      hotRank: 15,
      tags: ["棋类", "跳跃", "吃子"],
      coverA: "#ff6d83",
      coverB: "#7ce7ff",
    },
    {
      id: "sudoku",
      title: "迷你数独",
      description: "4x4 数独棋盘，填满每行每列和宫格。",
      genre: "棋盘益智",
      difficulty: "轻度烧脑",
      duration: "2-5 分钟",
      category: "棋类",
      icon: "4x4",
      coverLabel: "迷你数独",
      coverNote: "数字推理",
      hotRank: 16,
      tags: ["棋盘", "数独", "益智"],
      coverA: "#95a7ff",
      coverB: "#7ce7ff",
    },
    {
      id: "mines",
      title: "扫雷棋盘",
      description: "在小棋盘中避开地雷，清空安全格。",
      genre: "棋盘推理",
      difficulty: "中等",
      duration: "2-5 分钟",
      category: "棋类",
      icon: "✹",
      coverLabel: "避开地雷",
      coverNote: "数字推断",
      hotRank: 17,
      tags: ["棋盘", "扫雷", "推理"],
      coverA: "#ffd166",
      coverB: "#b85f30",
    },
    {
      id: "hanoi",
      title: "汉诺塔",
      description: "移动圆盘到目标柱，盘越小才能压在上面。",
      genre: "棋盘解谜",
      difficulty: "耐心",
      duration: "2-6 分钟",
      category: "棋类",
      icon: "III",
      coverLabel: "圆盘搬运",
      coverNote: "最少步数",
      hotRank: 18,
      tags: ["棋盘", "解谜", "逻辑"],
      coverA: "#ffd166",
      coverB: "#7ef0b2",
    },
    {
      id: "lights",
      title: "熄灯棋",
      description: "点击会联动周围格子，目标是熄灭全盘。",
      genre: "棋盘解谜",
      difficulty: "烧脑",
      duration: "1-3 分钟",
      category: "棋类",
      icon: "✧",
      coverLabel: "一键连动",
      coverNote: "全盘熄灯",
      hotRank: 19,
      tags: ["棋盘", "解谜", "连动"],
      coverA: "#7ce7ff",
      coverB: "#1f3b7a",
    },
    {
      id: "hexpawn",
      title: "兵卒棋",
      description: "3x3 小棋盘兵卒对战，吃掉对手或走到底线获胜。",
      genre: "微型棋类",
      difficulty: "简单",
      duration: "1 分钟",
      category: "棋类",
      icon: "♟",
      coverLabel: "兵卒冲线",
      coverNote: "小棋盘快战",
      hotRank: 20,
      tags: ["棋类", "快战", "吃子"],
      coverA: "#d8d8d8",
      coverB: "#3b3b3b",
    },
    {
      id: "xiangqi",
      title: "中国象棋",
      description: "完整棋子走法的单机象棋，红方先手，对战简单 AI。",
      genre: "传统棋类",
      difficulty: "中等偏上",
      duration: "6-12 分钟",
      category: "棋类",
      icon: "帅",
      coverLabel: "楚河汉界",
      coverNote: "红黑对弈",
      hotRank: 21,
      tags: ["象棋", "传统", "将帅"],
      coverA: "#f9d0aa",
      coverB: "#d44d4d",
    },
    {
      id: "junqi",
      title: "军棋",
      description: "简化军棋规则，保护军旗并用高阶军官压制电脑。",
      genre: "军棋策略",
      difficulty: "中等",
      duration: "4-8 分钟",
      category: "棋类",
      icon: "旗",
      coverLabel: "夺旗前线",
      coverNote: "简化军棋",
      hotRank: 22,
      tags: ["军棋", "军官", "夺旗"],
      coverA: "#9fb6d9",
      coverB: "#35567d",
    },
  ],
};
